# Generated by Django 2.2.14 on 2020-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='', max_length=70, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_icon',
            field=models.ImageField(blank=True, max_length=200, upload_to='media/uploads/article/%Y/%m/%d/'),
        ),
    ]
