# Generated by Django 2.2.14 on 2020-07-29 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200729_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(null=True, verbose_name='文本内容'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=70, null=True, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/uploads/article/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_from', to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
