# Generated by Django 2.2.14 on 2020-07-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='media/uploads/user/%Y/%m/%d/'),
        ),
    ]
